# Render deployment configuration
services:
  - type: web
    name: tresr-shopify-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_WEBHOOK_SECRET
        sync: false
      - key: SHOPIFY_STORE_DOMAIN
        value: becc05-b4.myshopify.com
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: DYNAMIC_ENV_ID
        value: b17e8631-c1b7-45d5-95cf-151eb5246423
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true